// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Gq9pX60N5qS3fXlAnVel9kcqTJmIx8A',
    appId: '1:392047081893:web:0d18a3f7e61a1987de904c',
    messagingSenderId: '392047081893',
    projectId: 'movies-app-ee05a',
    authDomain: 'movies-app-ee05a.firebaseapp.com',
    storageBucket: 'movies-app-ee05a.appspot.com',
    measurementId: 'G-R8BMEVN4RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIjKy-lFT3tfgWfTbYHmfuqehrOFfsHrs',
    appId: '1:392047081893:android:096045177794e421de904c',
    messagingSenderId: '392047081893',
    projectId: 'movies-app-ee05a',
    storageBucket: 'movies-app-ee05a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARQoqsS_eWDVfhorwH9sC6VHfTDUzeiD4',
    appId: '1:392047081893:ios:561da19179542b6dde904c',
    messagingSenderId: '392047081893',
    projectId: 'movies-app-ee05a',
    storageBucket: 'movies-app-ee05a.appspot.com',
    iosClientId: '392047081893-s813131rvmkh2lfirm7djubhnq8r69n2.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARQoqsS_eWDVfhorwH9sC6VHfTDUzeiD4',
    appId: '1:392047081893:ios:15c49c663739710cde904c',
    messagingSenderId: '392047081893',
    projectId: 'movies-app-ee05a',
    storageBucket: 'movies-app-ee05a.appspot.com',
    iosClientId: '392047081893-agn01bbmgv81svvsotnpc8tl0d1s9fej.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp.RunnerTests',
  );
}
